baseURL = "https://s4ik4t.github.io/devthread/"
languageCode = "en-us"
title = "DevThread"
theme = "soho"
publishDir = "docs"

[params]
author = "Saikat Sengupta"
description = "My Weblog"

gravatar = "shoikawt@gmail.com"

copyright = "Saikat Sengupta"
license = "CC BY-SA 4.0"
licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"

## Set custom theme color.
# themeColor = "#fc2803"

  ## Set as many as you want.
  [[params.socialIcons]]
  icon = "fa-linkedin"
  title = "Linkedin"
  url = "https://www.linkedin.com/in/saikatsengupta/"

  [[params.socialIcons]]
  icon = "fa-github"
  title = "GitHub"
  url = "#"

  [[params.socialIcons]]
  icon = "fa-twitter"
  title = "Twitter"
  url = "#"

  [[params.socialIcons]]
  icon = "fa-youtube"
  title = "YouTube"
  url = "#" 

  [[params.socialIcons]]
  icon = "fa-stack-overflow"
  title = "StackOverflow"
  url = "https://stackoverflow.com/users/1594823/"

[menu]

  [[menu.main]]
  name = "Posts"
  weight = 100
  identifier = "posts"
  url = "/posts/"

  [[menu.main]]
  name = "About"
  identifier = "about"
  weight = 300
  url = "/about/"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[markup]

  [markup.highlight]
  codeFences = true
  guessSyntax = false
  hl_Lines = ""
  lineNoStart = 1
  lineNos = false
  lineNumbersInTable = true
  noClasses = true
  style = "monokai"
  tabWidth = 4  